version: "3.9"

services:
  db3:
    build:
      context: .
      dockerfile: Dockerfile.db  
    container_name: my_postgres3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db3          
    ports:
      - "5433:5432"             
    volumes:
      - db3_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  

  app3:
    build: .
    container_name: lr3
    env_file: .env              
    volumes:
      - ./logs:/logs
    depends_on:
      - db3
    logging:
      driver: "none"

volumes:
  db3_data: